# Generated by Django 3.1.6 on 2021-06-30 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='client_peut_choisir_tous_les_plats',
            new_name='plat_au_choix',
        ),
        migrations.AddField(
            model_name='menu',
            name='plat_au_choix_quantite',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
