# Generated by Django 3.1.6 on 2021-06-30 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20210630_0218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='plat_au_choix_quantite',
        ),
        migrations.CreateModel(
            name='PlatAuChoix',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_au_choix_quantite', models.IntegerField(default=0, null=True)),
                ('categories', models.ManyToManyField(blank=True, to='restaurant.Categorie')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='details_plat_au_choix',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.platauchoix'),
        ),
    ]
