# Generated by Django 3.1.6 on 2021-07-01 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_horaire_inforestaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='disponibilite',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='menu',
            name='plat_au_choix',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='produit',
            name='disponibilite',
            field=models.BooleanField(default=False),
        ),
    ]
