# Generated by Django 3.1.6 on 2021-07-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_auto_20210701_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='inforestaurant',
            name='prix_minimum',
            field=models.FloatField(default=15),
        ),
    ]
