# Generated by Django 3.1.6 on 2021-07-04 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20210702_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulairecontact',
            name='prestation',
        ),
    ]
