# Generated by Django 3.1.6 on 2021-07-04 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_remove_formulairecontact_prestation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formulairecontact',
            name='prenom',
        ),
    ]
