# Generated by Django 3.1.6 on 2021-06-29 21:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=250)),
                ('ville', models.CharField(max_length=32)),
                ('code_postale', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ItemMenu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prix', models.FloatField(blank=True, default=0)),
                ('quantite', models.IntegerField(default=0)),
                ('composition', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ItemProduit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80)),
                ('prix', models.FloatField(blank=True, default=0)),
                ('quantite', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menus', models.ManyToManyField(blank=True, to='paiement.ItemMenu')),
                ('produits', models.ManyToManyField(blank=True, to='paiement.ItemProduit')),
            ],
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_commande', models.DateTimeField(auto_now_add=True)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('prix_totale', models.FloatField(default=0.0)),
                ('est_vue', models.BooleanField(default=False)),
                ('est_livre', models.BooleanField(default=False)),
                ('reference', models.CharField(default='', max_length=5, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='paiement.client')),
                ('panier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='paiement.panier')),
            ],
        ),
    ]
