# Generated by Django 3.1.6 on 2021-07-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paiement', '0002_commande_methode_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commande',
            name='reference',
            field=models.CharField(default='', max_length=6, null=True),
        ),
    ]
